export const sampleAddressRecord = {
  pin: "12345678901234",
  housenumber: "123",
  streetname: "MAIN ST",
  address: "123 MAIN ST",
  city: "Chicago",
  state: "IL",
  zip: "60601",
  owner_id: "OWN1",
  owner_name: "Sample Owner",
  mailing_address: "123 MAIN ST",
  mailing_city: "Chicago",
  mailing_state: "IL",
  mailing_zip: "60601",
  units_res: 10,
  land_class: "R",
  building_class: "A",
  lat: 41.88,
  lng: -87.63,
  ward: "1",
  community_area: "Loop",
  census_tract: "0001",
  permits_total: 2,
  violations_open: 1,
  violations_total: 3,
  requests_311_total: 4,
};
