SELECT
    p.pin,
    p.housenumber,
    p.streetname,
    p.address,
    p.city,
    p.state,
    p.zip,
    p.owner_id,
    p.owner_name,
    p.mailing_address,
    p.mailing_city,
    p.mailing_state,
    p.mailing_zip,
    p.units_res,
    p.land_class,
    p.building_class,
    p.lat,
    p.lng,
    p.ward,
    p.community_area,
    p.census_tract,
    i.permits_total,
    i.violations_open,
    i.violations_total,
    i.requests_311_total,
    tax.annual_tax_sale_count,
    tax.scavenger_tax_sale_count,
    tax.tax_sale_event_count,
    tax.latest_tax_sale_year,
    tax.latest_tax_sale_buyer_name,
    tax.latest_tax_sale_sold_at_sale,
    tax.total_tax_sale_amount_paid,
    rec.recorder_doc_count,
    rec.mortgage_doc_count,
    rec.quitclaim_doc_count,
    rec.foreclosure_doc_count,
    rec.latest_recorder_doc_date,
    rec.latest_mortgage_date,
    rec.latest_mortgage_amount,
    rec.latest_quitclaim_date,
    rec.latest_quitclaim_amount
FROM wow_parcels AS p
LEFT JOIN wow_indicators AS i USING(pin)
LEFT JOIN wow_tax_sale_summary AS tax USING(pin)
LEFT JOIN wow_recorder_summary AS rec USING(pin)
WHERE p.pin = %(pin)s;
