from typing import NamedTuple


class ChiViolations(NamedTuple):
    id: str = ''
    violation_last_modified_date: str = ''
    violation_date: str = ''
    violation_code: str = ''
    violation_status: str = ''
    violation_status_date: str = ''
    violation_description: str = ''
    violation_location: str = ''
    violation_inspector_comments: str = ''
    violation_ordinance: str = ''
    inspector_id: str = ''
    inspection_number: str = ''
    inspection_status: str = ''
    inspection_waived: str = ''
    inspection_category: str = ''
    department_bureau: str = ''
    address: str = ''
    street_number: str = ''
    street_direction: str = ''
    street_name: str = ''
    street_type: str = ''
    property_group: str = ''
    ssa: str = ''
    latitude: str = ''
    longitude: str = ''
    location: str = ''
